[package]
name = "batt-post"
version = "0.1.0"
authors = ["Will Springer"]
description = "Send battery status somewhere"
edition = "2018"
license = "Apache-2.0 OR MIT"

[dependencies]
battery = "0.7.1"
multisock = "0.1.0"
